<?PHP
$productos =     [
    [
        "id" => 1,
        "personaje" => "star-wars",
        "titulo" => "La Amenaza Fantasma",
        "capitulo" => 1,
        "volumen" => 1,
        "publicacion" => "Mayo 1999",
        "guion" => "George Lucas",
        "arte" => "John Williams",
        "bajada" => "Explora los orígenes de Anakin Skywalker y el surgimiento del malvado Darth Maul. La galaxia se sumerge en la política y la guerra.",
        "portada" => "img/covers/capitulo-1.jpg",
        "precio" => 2000
    ],
    [
        "id" => 2,
        "personaje" => "star-wars",
        "titulo" => "El Ataque de los Clones",
        "capitulo" => 2,
        "volumen" => 2,
        "publicacion" => "Mayo 2002",
        "guion" => "George Lucas y Jonathan Hales",
        "arte" => "John Williams",
        "bajada" => "La galaxia se encuentra al borde de la guerra mientras los Jedi intentan mantener la paz. Anakin Skywalker comienza su viaje hacia la oscuridad.",
        "portada" => "img/covers/capitulo-2.jpg",
        "precio" => 2100
    ],
    [
        "id" => 3,
        "personaje" => "star-wars",
        "titulo" => "La Venganza de los Sith",
        "capitulo" => 3,
        "volumen" => 3,
        "publicacion" => "Mayo 2005",
        "guion" => "George Lucas",
        "arte" => "John Williams",
        "bajada" => "La República se desmorona mientras Anakin Skywalker cae al lado oscuro y se convierte en Darth Vader. El Imperio Galáctico se alza.",
        "portada" => "img/covers/capitulo-3.jpg",
        "precio" => 2500
    ],
    [
        "id" => 4,
        "personaje" => "star-wars",
        "titulo" => "Una Nueva Esperanza",
        "capitulo" => 4,
        "volumen" => 1,
        "publicacion" => "Mayo 1977",
        "guion" => "George Lucas",
        "arte" => "John Williams",
        "bajada" => "Únete a Luke Skywalker, la Princesa Leia y Han Solo en su lucha contra el malvado Imperio Galáctico. Una historia épica de aventuras, amistad y la Fuerza.",
        "portada" => "img/covers/capitulo-4.jpg",
        "precio" => 2200
    ],
    [
        "id" => 5,
        "personaje" => "star-wars",
        "titulo" => "El Imperio Contraataca",
        "episodio" => 5,
        "volumen" => 2,
        "publicacion" => "Mayo 1980",
        "guion" => "George Lucas",
        "arte" => "John Williams",
        "bajada" => "La Rebelión enfrenta desafíos mayores mientras Luke entrena con Yoda para convertirse en un Jedi. Mientras tanto, el Imperio contraataca con fuerza implacable.",
        "portada" => "img/covers/capitulo-5.jpg",
        "precio" => 2300
    ],
    [
        "id" => 6,
        "personaje" => "star-wars",
        "titulo" => "El Retorno del Jedi",
        "episodio" => 6,
        "volumen" => 3,
        "publicacion" => "Mayo 1983",
        "guion" => " George Lucas",
        "arte" => "John Williams",
        "bajada" => "La saga original llega a su conclusión con la batalla final entre las fuerzas de la Rebelión y el Imperio. Luke enfrenta a Darth Vader y al Emperador en un enfrentamiento épico.",
        "portada" => "img/covers/capitulo-6.jpg",
        "precio" => 2400
    ],
    [
        "id" => 7,
        "personaje" => "star-wars",
        "titulo" => "El Despertar de la Fuerza",
        "episodio" => 7,
        "volumen" => 7,
        "publicacion" => "Diciembre 2015",
        "guion" => "George lucas",
        "arte" => "John Williams",
        "bajada" => "Nuevos héroes y viejas leyendas se unen en la lucha contra la malvada Primera Orden. Rey, Finn y Poe enfrentan un oscuro despertar de la Fuerza.",
        "portada" => "img/covers/capitulo-7.jpg",
        "precio" => 2600
    ],
    [
        "id" => 8,
        "personaje" => "star-wars",
        "titulo" => "Los Últimos Jedi",
        "episodio" => 8,
        "volumen" => 8,
        "publicacion" => "Diciembre 2017",
        "guion" => "George lucas",
        "arte" => "John Williams",
        "bajada" => "La Resistencia lucha por su supervivencia mientras Rey busca respuestas sobre su conexión con la Fuerza. Luke Skywalker enfrenta su pasado.",
        "portada" => "img/covers/capitulo-8.jpg",
        "precio" => 2700
    ],
    [
        "id" => 9,
        "personaje" => "star-wars",
        "titulo" => "El Ascenso de Skywalker",
        "episodio" => 9,
        "volumen" => 9,
        "publicacion" => "Diciembre 2019",
        "guion" => "George Lucas",
        "arte" => "John Williams",
        "bajada" => "La saga Skywalker llega a su fin. Rey enfrenta a Palpatine mientras la Resistencia se prepara para la batalla final contra la Primera Orden.",
        "portada" => "img/covers/capitulo-9.jpg",
        "precio" => 2800
    ],
    [
        "id" => 10,
        "personaje" => "star-wars",
        "titulo" => "El ataque de los clones",
        "episodio" => 10,
        "volumen" => 10,
        "publicacion" => "abril 2008",
        "guion" => "George lucas",
        "arte" => "john williams",
        "bajada" => "En el Senado Galáctico reina la inquietud. Varios miles de sistemas solares han declarado su intención de abandonar la República.",
        "portada" => "img/covers/La-guerra-de-los-clones-10.jpg",
        "precio" => "3000",
    ],
    [
        "id" => 11,
        "personaje" => "star-wars",
        "titulo" => "Rogue One: Una Historia de Star Wars",
        "episodio" => 11,
        "volumen" => 11,
        "publicacion" => "Diciembre 2016",
        "guion" => "George Lucas",
        "arte" => "John williams",
        "bajada" => "En los albores de la Rebelión, un grupo de héroes inverosímiles se une para robar los planos de la Estrella de la Muerte y cambiar el destino de la galaxia.",
        "portada" => "img/covers/Rogue-One-12.jpg",
        "precio" => 3200
    ],
    [
        "id" => 12,
        "personaje" => "star-wars",
        "titulo" => "Han Solo: Una Historia de Star Wars",
        "episodio" => 12,
        "volumen" => 12,
        "publicacion" => "Mayo 2018",
        "guion" => "George Lucas",
        "arte" => "John williams",
        "bajada" => "Acompaña a un joven Han Solo en sus primeras aventuras, desde su encuentro con Chewbacca hasta los orígenes de su amistad con Lando Calrissian.",
        "portada" => "img/covers/Han-Solo-11.jpg",
        "precio" => 3100
    ],
    
    [
        "id" => 13,
        "personaje" => "star-wars",
        "titulo" => "La Leyenda de Yoda",
        "episodio" => 13,
        "volumen" => 13,
        "publicacion" => "Septiembre 2019",
        "guion" => "George Lucas",
        "arte" => "John Williams",
        "bajada" => "Sumérgete en las historias legendarias de Yoda, el sabio maestro Jedi. Desde sus primeros días hasta sus hazañas más asombrosas, este cómic revela los secretos de la Fuerza.",
        "portada" => "img/covers/especial-13.jpg",
        "precio" => 2800
    ],
    [
        "id" => 14,
        "personaje" => "star-wars",
        "titulo" => "El Último Padawan",
        "episodio" => 14,
        "volumen" => 14,
        "publicacion" => "Noviembre 2015",
        "guion" => "George Lucas",
        "arte" => "John Williams",
        "bajada" => "Descubre la historia de Kanan Jarrus, el último padawan Jedi tras la ejecución de la Orden 66. ¿Cómo sobrevivió a la purga Jedi y se convirtió en el héroe que conocemos?",
        "portada" => "img/covers/especial-14.jpg",
        "precio" => 2600
    ],
    [
        "id" => 15,
        "personaje" => "star-wars",
        "titulo" => "La Senda Jedi",
        "episodio" => 15,
        "volumen" => 15,
        "publicacion" => "Marzo 2021",
        "guion" => "George Lucas",
        "arte" => "John Williams",
        "bajada" => "Explora los caminos de la Senda Jedi a través de las eras. Desde los antiguos guardianes hasta los héroes contemporáneos, este cómic celebra la diversidad y el legado de la Orden Jedi.",
        "portada" => "img/covers/especial-15.jpg",
        "precio" => 2900
    ]
    
    ];